export interface Data {
  id: number;
  images: string[];
  title: string;
  location: string;
  price: string;
  priceValue: number; // numeric for filtering
  type: "House" | "Rent" | "Land";
  beds: number;
  baths: number;
  sqft: string;
  sqftValue: number; // numeric for filtering
  description: string;
  tag?: "New Listing" | "Price Drop" | "Hot Deal" | "Exclusive";
  lat: number;
  lng: number;
}

export const listData: Data[] = [
  {
    id: 1,
    images: ["/img1.png", "/img2.png"],
    title: "The Meridian Residence",
    location: "Victoria Island, Lagos",
    price: "₦250,000,000",
    priceValue: 250000000,
    type: "House",
    beds: 5,
    baths: 4,
    sqft: "4,200",
    sqftValue: 4200,
    description:
      "A stunning waterfront residence with panoramic ocean views, bespoke finishes, and a private infinity pool on Victoria Island.",
    tag: "Exclusive",
    lat: 6.4281,
    lng: 3.4219,
  },
  {
    id: 2,
    images: ["/img2.png", "/img3.png"],
    title: "Skyline Penthouse",
    location: "Lekki Phase 1, Lagos",
    price: "₦1,800,000 / mo",
    priceValue: 1800000,
    type: "Rent",
    beds: 4,
    baths: 3,
    sqft: "3,800",
    sqftValue: 3800,
    description:
      "Sophisticated full-floor penthouse in the heart of Lekki with floor-to-ceiling glass and a wraparound terrace overlooking the Lagos skyline.",
    tag: "Hot Deal",
    lat: 6.4474,
    lng: 3.4895,
  },
  {
    id: 3,
    images: ["/img3.png", "/img1.png"],
    title: "Emerald Court Villa",
    location: "Ikoyi, Lagos",
    price: "₦400,000,000",
    priceValue: 400000000,
    type: "House",
    beds: 6,
    baths: 6,
    sqft: "7,500",
    sqftValue: 7500,
    description:
      "Grand colonial-style villa in the prestigious Ikoyi enclave, featuring a private cinema, gym, and manicured gardens.",
    tag: "New Listing",
    lat: 6.451,
    lng: 3.4375,
  },
  {
    id: 4,
    images: ["/img1.png", "/img3.png"],
    title: "Harbour View Estate",
    location: "Eko Atlantic, Lagos",
    price: "₦550,000,000",
    priceValue: 550000000,
    type: "House",
    beds: 7,
    baths: 8,
    sqft: "10,200",
    sqftValue: 10200,
    description:
      "Landmark luxury estate on Eko Atlantic — the future of Lagos — with private harbour access and world-class smart-home technology.",
    tag: "Exclusive",
    lat: 6.4107,
    lng: 3.3956,
  },
  {
    id: 5,
    images: ["/img2.png", "/img1.png"],
    title: "Greenfield Acres",
    location: "Epe, Lagos",
    price: "₦45,000,000",
    priceValue: 45000000,
    type: "Land",
    beds: 0,
    baths: 0,
    sqft: "25 Acres",
    sqftValue: 25,
    description:
      "Prime agricultural and development land in Epe with verified C of O — ideal for an estate development or agribusiness venture.",
    tag: "Price Drop",
    lat: 6.5857,
    lng: 3.9839,
  },
  {
    id: 6,
    images: ["/img3.png", "/img2.png"],
    title: "Coral Gardens Apartment",
    location: "Ajah, Lagos",
    price: "₦550,000 / mo",
    priceValue: 550000,
    type: "Rent",
    beds: 3,
    baths: 2,
    sqft: "1,600",
    sqftValue: 1600,
    description:
      "Beautifully furnished serviced apartment in a gated estate with 24-hour power, swimming pool, and easy access to the Lekki-Epe Expressway.",
    lat: 6.4698,
    lng: 3.5747,
  },
  {
    id: 7,
    images: ["/img1.png", "/img2.png"],
    title: "Palm Grove Terrace",
    location: "Banana Island, Lagos",
    price: "₦620,000,000",
    priceValue: 620000000,
    type: "House",
    beds: 5,
    baths: 5,
    sqft: "6,300",
    sqftValue: 6300,
    description:
      "Prestigious terrace home on the exclusive Banana Island with a private pool, rooftop deck, and 24-hour concierge service.",
    tag: "Hot Deal",
    lat: 6.46,
    lng: 3.4317,
  },
  {
    id: 8,
    images: ["/img2.png", "/img3.png"],
    title: "Marina Loft Studio",
    location: "Lagos Island, Lagos",
    price: "₦380,000 / mo",
    priceValue: 380000,
    type: "Rent",
    beds: 1,
    baths: 1,
    sqft: "750",
    sqftValue: 750,
    description:
      "Contemporary studio loft with high ceilings and exposed brickwork, walking distance to the Lagos Marina and central business district.",
    tag: "New Listing",
    lat: 6.453,
    lng: 3.3958,
  },
  {
    id: 9,
    images: ["/img3.png", "/img1.png"],
    title: "Westland Prime Plot",
    location: "Ikeja GRA, Lagos",
    price: "₦120,000,000",
    priceValue: 120000000,
    type: "Land",
    beds: 0,
    baths: 0,
    sqft: "5 Acres",
    sqftValue: 5,
    description:
      "Strategic commercial/residential plot in the coveted Ikeja GRA with full government approval — ready for immediate development.",
    lat: 6.6018,
    lng: 3.3515,
  },
  {
    id: 10,
    images: ["/img1.png", "/img3.png"],
    title: "The Riviera Duplex",
    location: "Oniru, Lagos",
    price: "₦900,000 / mo",
    priceValue: 900000,
    type: "Rent",
    beds: 4,
    baths: 3,
    sqft: "2,800",
    sqftValue: 2800,
    description:
      "Exquisite waterside duplex in the Oniru Royal Estate with a private garden, sea breeze balcony, and fully fitted gourmet kitchen.",
    tag: "Price Drop",
    lat: 6.4363,
    lng: 3.4647,
  },
  {
    id: 11,
    images: ["/img2.png", "/img1.png"],
    title: "The Crown Mansion",
    location: "Magodo GRA, Lagos",
    price: "₦185,000,000",
    priceValue: 185000000,
    type: "House",
    beds: 6,
    baths: 5,
    sqft: "5,100",
    sqftValue: 5100,
    description:
      "A commanding mansion in Magodo GRA Phase 2 with a multi-car garage, home office suite, and lush private compound.",
    tag: "New Listing",
    lat: 6.6069,
    lng: 3.3874,
  },
  {
    id: 12,
    images: ["/img3.png", "/img2.png"],
    title: "Atlantic Crest Land",
    location: "Badagry, Lagos",
    price: "₦28,000,000",
    priceValue: 28000000,
    type: "Land",
    beds: 0,
    baths: 0,
    sqft: "10 Acres",
    sqftValue: 10,
    description:
      "Serene beachfront land parcel in Badagry — perfect for a resort development or private seafront retreat. C of O available.",
    tag: "Price Drop",
    lat: 6.416,
    lng: 2.8894,
  },
];
